# Generated by Django 3.0.5 on 2020-05-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khu_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khuclass',
            table='class',
        ),
    ]
