# Generated by Django 3.0.5 on 2020-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField()),
                ('student_num', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
