# Generated by Django 3.0.5 on 2020-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khuclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField()),
                ('student_num', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField()),
                ('classes', models.ManyToManyField(blank=True, to='khu_class.Khuclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='khuclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='khu_class.Student'),
        ),
    ]
